config/routes.rb
Rails.application.routes.draw do
  get '/homepage' => 'homepage#index'

  get '/songs' => 'songs#index'
  get '/songs/new' => 'songs#new'
  get '/songs/sort' => 'songs#sort'

  resources :songs

  root 'homepage#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/song.rb
class Song < ApplicationRecord


  validates :artist,
            length: { in: 1..50,
                      too_long: 'maag maar maximaal %{count} karakters lang zijn.',
                      too_short: 'moet minimaal %{count} karakter lang zijn.'
                    }
  validates :name,
            length: { in: 1..50,
                      too_long: 'maag maar maximaal %{count} karakters lang zijn.',
                      too_short: 'moet minimaal %{count} karakter lang zijn.'
                    }
  validates :genre,
            length: { in: 1..20,
                      too_long: 'maag maar maximaal %{count} karakters lang zijn.',
                      too_short: 'moet minimaal %{count} karakter lang zijn.'
                    }
  validates :description,
            length: { in: 1..300,
                      too_long: 'maag maar maximaal %{count} karakters lang zijn.',
                      too_short: 'moet minimaal %{count} karakter lang zijn.'
                    }
  validates :album,
            length: { in: 1..25,
                      too_long: 'maag maar maximaal %{count} karakters lang zijn.',
                      too_short: 'moet minimaal %{count} karakter lang zijn.'
                    }
  validates :score,
            numericality: { only_integer: true,
                            greater_than_or_equal_to: 0,
                            less_than: 12
                          }

  validates :rating,
            numericality: { only_integer: true,
                            greater_than_or_equal_to: 0,
                            less_than: 9
                          }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all
  end

  def show
    @song = Song.find(params[:id])
  end

  def new
    @song = Song.new
  end

  def edit
    @song = Song.find(params[:id])
  end

  def create
    @song = Song.new(song_params)

    if @song.save
      redirect_to @song
    else
      render 'new'
    end
  end

  def update
    @song = Song.find(params[:id])

    if @song.update(song_params)
      redirect_to @song
    else
      render 'edit'
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    redirect_to '/songs'
  end

  def sort
    if params[:search]
      @songs = Song.where("artist LIKE ? OR name LIKE ? OR genre LIKE ? OR score LIKE ? OR rating LIKE ?",
      "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%")
    else
      @songs = Song.all
    end
  end

  private
  def song_params
    params.require(:song).permit(:artist, :name, :genre, :description, :album, :score, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catalogus_helper.rb
module CatalogusHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/homepage/index.html.erb
<div class="content">
  <h3 class='sub_title'>Welkom</h3>
  <p class="content_text">
    Deze site bevat een volledige database aan nummers.
  </p>
  <ul>
    <li>In de catalogus staan alle nummers op een rijtje.</li>
    <li>Wil je een nummer toevoegen? Druk op 'Voeg nummer toe' en vul alle gegevens in.</li>
    <li>Bij 'Sorteren' kunnen je zoeken naar specifieke eigenschappen, zoals genres, albums en ratings.</li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Muziek</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <h1 class="title">Muziek Database</h1>
    <div id="navigation_bar">
      <%= link_to 'Homepage', controller: 'homepage', action: 'index' %>
      <%= link_to 'Catalogus', controller: 'songs', action: 'index' %>
      <%= link_to 'Voeg nummer toe', controller: 'songs', action: 'new' %>
      <%= link_to 'Sorteren', controller: 'songs', action: 'sort' %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/songs/edit.html.erb
<div class="content">
  <h1 class="sub_title">Pas een nummer aan</h1>
  <div class="form">
    <%= form_with(model: @song, local: true) do |form| %>
    <% if @song.errors.any? %>
      <div id="error_explanation">
        <h3>
          <%= pluralize(@song.errors.count, "error") %> zorgden ervoor dat je
          dit nummer niet kon opslaan:
        </h3>
        <ul>
          <% @song.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <p id="new_song_artist">
      <%= form.label :artist %>&nbsp;
      <%= form.text_field(:artist, :placeholder => 'Puppet', :id => 'tf_artist') %>
    </p>
    <p id="new_song_name">
      <%= form.label :name %>&nbsp;
      <%= form.text_field(:name, :placeholder => 'Bigger Picture', :id => 'tf_name') %>
    </p>
    <p id="new_song_genre">
      <%= form.label :genre %>&nbsp;
      <%= form.text_field(:genre, :placeholder => 'Indie Dance', :id => 'tf_genre') %>
    </p>
    <div id="new_song_description">
      <%= form.label :description %>&nbsp;
      <div class="question" id="question_description">
        <span>&nbsp;?&nbsp;</span>
        <p class="toh" id="toh_description">
          <em>Probeer te beschrijven hoe het nummer klinkt; is het emotioneel,
          of niet? Gaat hij hard, of niet? Je hoeft niet per se een hele
          bijbel te schrijven.</em>
        </p>
      </div><br>
      <%= form.text_area(:description, :id => 'tf_description',
        :class => 'tf', :placeholder => 'Ik ben zo diep geraakt!',
        :rows => '5', :cols => '50') %>
      <br>
    </div>
    <div id="new_song_album">
      <%= form.label :album %>&nbsp;
      <div class="question" id="question_album">
        <span>&nbsp;?&nbsp;</span>
        <p class="toh" id="toh_album">
          <em>De naam van het album invullen is niet zo moeilijk, toch?
          Als het nummer een single is, type dan 'Single' in. Het nummer
          kan deel zijn van een album en tevens afzonderlijk zijn released.
          Vul dan alsnog de naam van het album in.</em>
        </p>
      </div><br>
      <%= form.text_field(:album, :id => 'tf_album', :class => 'tf',
        :placeholder => 'Fear is Fleeting EP') %>
      <br>
    </div>
    <div id="new_song_score">
      <%= form.label :score %>&nbsp;
      <div class="question" id="question_score">
        <span>&nbsp;?&nbsp;</span>
        <p class="toh" id="toh_score">
          <em>Simpelweg hoe goed Lieke het nummer vindt. Van 0 tot en met 10. Tien
          natuurlijk je absoluut favoriete nummer en nul als je bijna moet
          kotsen.</em>
        </p>
      </div><br>
      <span id="score">Liekes score uit 10 --></span>&nbsp;
      <%= form.number_field(:score, :placeholder => '0', :id => 'tf_score',
        :class => 'tf') %>
      <br>
    </div>
    <div id="new_song_rating">
      <%= form.label :rating %>&nbsp;
      <div class="question" id="question_rating">
        <span>&nbsp;?&nbsp;</span>
        <p class="toh" id="toh_rating">
          <em>Hoe goed Timon het nummer vind. 0 tot en met 7. 0 voor in geen enkele Tier.
          1 voor in Tier 1, enz. Krijgt een nummer 7, staat het in zijn Top 25.</em>
        </p>
      </div><br>
      <span id="rating">Timons score uit 7 --></span>&nbsp;
      <%= form.number_field(:rating, :placeholder => '0', :id => 'tf_rating',
        :class => 'tf') %>
      <br>
    </div>
    <p id="new_song_submit">
      <%= form.submit %>
    </p>
    <% end %>
  </div>
</div>

app/views/songs/index.html.erb

<table class="content">
  <tr>
    <th>Artiest(en)</th>
    <th>Naam</th>
    <th>Album</th>
    <th>Genre</th>
    <th>Rating</th>
    <th colspan="3"></th>
  </tr>
  <% @songs.each do |song| %>
  <tr>
    <td><%= song.artist %></td>
    <td><%= song.name %></td>
    <td><%= song.album %></td>
    <td><%= song.genre %></td>
    <td><%= song.rating %></td>
    <td><%= link_to 'Show entry', song_path(song) %></td>
    <td><%= link_to 'Edit entry', edit_song_path(song) %> </td>
    <td><%= link_to 'Delete entry', song_path(song),
            method: :delete,
            data: { confirm: 'Weet je zeker dat je dit nummer wilt verwijderen?' }%></td>
  </tr>
  <% end %>
</table>

app/views/songs/new.html.erb
<div class="content">
  <h1 class="sub_title">Voeg een nummer toe</h1>
  <div class="form">
    <%= form_with scope: :song, url: songs_path, local: true do |form| %>
    <% if @song.errors.any? %>
      <div id="error_explanation">
        <h3>
          <%= pluralize(@song.errors.count, "error") %> zorgden ervoor dat je
          dit nummer niet kon opslaan:
        </h3>
        <ul>
          <% @song.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

      <p id="new_song_artist">
        <%= form.label :artist %>&nbsp;
        <%= form.text_field(:artist, :placeholder => 'Puppet', :id => 'tf_artist') %>
      </p>
      <p id="new_song_name">
        <%= form.label :name %>&nbsp;
        <%= form.text_field(:name, :placeholder => 'Bigger Picture', :id => 'tf_name') %>
      </p>
      <p id="new_song_genre">
        <%= form.label :genre %>&nbsp;
        <%= form.text_field(:genre, :placeholder => 'Indie Dance', :id => 'tf_genre') %>
      </p>
      <div id="new_song_description">
        <%= form.label :description %>&nbsp;
        <div class="question" id="question_description">
          <span>&nbsp;?&nbsp;</span>
          <p class="toh" id="toh_description">
            <em>Probeer te beschrijven hoe het nummer klinkt; is het emotioneel,
            of niet? Gaat hij hard, of niet? Je hoeft niet per se een hele
            bijbel te schrijven.</em>
          </p>
        </div><br>
        <%= form.text_area(:description, :id => 'tf_description',
          :class => 'tf', :placeholder => 'Ik ben zo diep geraakt!',
          :rows => '5', :cols => '50') %>
        <br>
      </div>
      <div id="new_song_album">
        <%= form.label :album %>&nbsp;
        <div class="question" id="question_album">
          <span>&nbsp;?&nbsp;</span>
          <p class="toh" id="toh_album">
            <em>De naam van het album invullen is niet zo moeilijk, toch?
            Als het nummer een single is, type dan 'Single' in. Het nummer
            kan deel zijn van een album en tevens afzonderlijk zijn released.
            Vul dan alsnog de naam van het album in.</em>
          </p>
        </div><br>
        <%= form.text_field(:album, :value => 'Single', :id => 'tf_album',
          :class => 'tf', :placeholder => 'Fear is Fleeting EP') %>
        <br>
      </div>
      <div id="new_song_score">
        <%= form.label :score %>&nbsp;
        <div class="question" id="question_score">
          <span>&nbsp;?&nbsp;</span>
          <p class="toh" id="toh_score">
            <em>Simpelweg hoe goed Lieke het nummer vindt. Van 0 tot en met 10. Tien
            natuurlijk je absoluut favoriete nummer en nul als je bijna moet
            kotsen.</em>
          </p>
        </div><br>
        <span id="score">Liekes score uit 10 --></span>&nbsp;
        <%= form.number_field(:score, :value => '11', :id => 'tf_score',
          :class => 'tf') %>
        <br>
      </div>
      <div id="new_song_rating">
        <%= form.label :rating %>&nbsp;
        <div class="question" id="question_rating">
          <span>&nbsp;?&nbsp;</span>
          <p class="toh" id="toh_rating">
            <em>Hoe goed Timon het nummer vind. 0 tot en met 7. 0 voor in geen enkele Tier.
            1 voor in Tier 1, enz. Krijgt een nummer 7, staat het in zijn Top 25.</em>
          </p>
        </div><br>
        <span id="rating">Timons score uit 7 --></span>&nbsp;
        <%= form.number_field(:rating, :value => '8', :id => 'tf_rating',
          :class => 'tf') %>
        <br>
      </div>
      <p id="new_song_submit">
        <%= form.submit %>
      </p>
    <% end %>
  </div>
</div>

app/views/songs/show.html.erb
<div class="content">
  <p class="song_title">
    <%= @song.artist %> - <%= @song.name %>
  </p>
  <p class="song_description">
    <%= @song.description %>
  </p><br>
  <p class="extra_info_title"><em>Extra informatie:</em></p>
  <div class="extra_information">
    Genre: <%= @song.genre %><br>
    Album: <%= @song.album %><br>
    Score: <%= @song.score %><br>
    Rating: <%= @song.rating %>
  </div>
  <br><br>
  <div class="links_container">
    <%= link_to 'Back', '/songs' %>&nbsp;|&nbsp;
    <%= link_to 'Edit', edit_song_path(@song) %>&nbsp;|&nbsp;
    <%= link_to 'Destroy', song_path(@song),
        method: :delete,
        data: { confirm: 'Weet je zeker dat je dit nummer wilt verwijderen?' } %>
  </div>
</div>

app/views/songs/sort.html.erb

<div class="content">
  <div  id='search_container'>
    <%= form_tag songs_sort_path, method: :get do %>
      <%= submit_tag 'Search', :name => nil, :id => 'search_submit' %>
      <%= text_field_tag :search, params[:search], :id => 'search_bar', :placeholder => 'Zoeken...' %>
      <!-- <input type="text" id="search_bar" placeholder="Zoeken..."> -->
    <% end %>
  </div>
  <table class="output">
    <tr>
      <th>Nummer</th>
      <th>Genre</th>
      <th>Score</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
    <% @songs.each do |song| %>
    <tr>
      <td><%= song.artist %> - <%= song.name %></td>
      <td><%= song.genre %></td>
      <td><%= song.score %></td>
      <td><%= song.rating %></td>
      <td><%= link_to 'Show entry', song_path(song) %></td>
      <td><%= link_to 'Edit entry', edit_song_path(song) %> </td>
      <td><%= link_to 'Delete entry', song_path(song),
              method: :delete,
              data: { confirm: 'Weet je zeker dat je dit nummer wilt verwijderen?' }%></td>
    </tr>
    <% end %>
  </table>
</div>